### ISSUE TITLE
Git clone command is wrong

### ISSUE THREAD

**Issue by Egwor** [mrzool/cv-boilerplate#3]
This clone command doesn't work for me:

```
git clone git@github.com:mrzool/cv-boilerplate.git && cd cv-boilerplate && rm -rf .git
Cloning into 'cv-boilerplate'...
Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I think you want:

```
git clone https://github.com/mrzool/cv-boilerplate.git && cd cv-boilerplate && rm -rf .git
```

**Comment by mrzool** [comment]
Thanks for reporting this. The command is not wrong, the issue is that you probably didn't set up an SSH key on your machine. Since that could be the case for a lot of other people and [Github recommends HTTPS over SSH](https://help.github.com/articles/set-up-git/#connecting-over-https-recommended), I'm going to change the command to reflect this as you suggested.

Thanks!
